$(document).ready(function () {
    $("form").validate({
        rules:{
            user:{
                required:true,
                rangelength:[6,16],
                remote:{
                    type:"post",
                    url:"../php/rege_yanzhen.php",
                    dataType:"json",
                }
            },
            password:{
                required:true,
                rangelength:[6,16],
            },
            password2:{
                required:true,
                rangelength:[6,16],
                equalTo:"#password"
            },
            code:{
                required:true
            }
        },
        messages:{
            user:{
                required:"用户名必填",
                rangelength:"用户名不能少于6位",
                remote:"用户名已存在"
            },
            password:{
                required:"密码必填",
                rangelength:"密码不能少于6位"
            },
            password2:{
                required:"密码必填",
                rangelength:"用户名不能少于6位",
                equalTo:"两次密码输入不一致"
            },
            code:{
                required:"验证码必填"
            }
        }
    })
})